### ISSUE TITLE
Removes all dependencies >.<

### ISSUE THREAD

**Issue by rippedspine** [JamesKyburz/dependency-sync#30]
Will remove all dependencies when run on nodemon restart event

nodemon.json
```javascript
{
  "events": {
      "restart": "yarn run missing"
  }
}
```

package.json
```javascript
{
  "scripts": {
    "missing": "dependency-sync --once",
    "dev": "nodemon index.js",
  },
  "depencency-sync": {
    "yarn": { "args": [] }
  }
}
```

index.js
```javascript
require('dotenv').config()

const start = require('./app')

if (!process.env.API_TOKEN) {
  require('./generate-envfile')(start)
} else {
  start()
}
```

**Comment by JamesKyburz** [comment]
How does your missing command look?

The argument parsing in this module could be be improved! The order is important.

This will work

```sh
    "missing": "dependency-sync index.js --yarn --debug --once"
```

This won't
```sh
    "missing": "dependency-sync --yarn --debug --once index.js"
```

**Comment by rippedspine** [comment]
Did not provide an entrypoint at all, as you can see in the above comment. So that should explain why it removes all dependencies. :woman_facepalming: 

But maybe it should use the default entry file in package.json if none is provided? :)

**Comment by JamesKyburz** [comment]
@rippedspine yeah :) I have made a little bit better by adding an entrypoint if missing.

It will either use the package.json main or index.js
